package nl.breun.doctor_pom;

import edu.umd.cs.findbugs.annotations.Nullable;
import org.apache.maven.model.Model;

import java.io.File;

/**
 * This class represents a Maven Project Object Model. It contains both a reference to the POM file and a raw parsed
 * object {@link Model} generated by Maven's own POM parser.
 */
public class ProjectObjectModel {

    @Nullable
    private File pomFile;

    @Nullable
    private Model rawModel;

    public ProjectObjectModel(@Nullable File pomFile, @Nullable Model rawModel) {
        this.pomFile = pomFile;
        this.rawModel = rawModel;
    }

    @Nullable
    public File getPomFile() {
        return pomFile;
    }

    public void setPomFile(File pomFile) {
        this.pomFile = pomFile;
    }

    @Nullable
    public Model getRawModel() {
        return rawModel;
    }

    public void setRawModel(Model rawModel) {
        this.rawModel = rawModel;
    }
}
